List<String> nombres = [
  'Juan',
  'Pedro',
  'Anuar',
  'Jimena',
  'Amanda',
  'Arturo',
  'Sebas',
  'Gabriel',
  'El borracho',
  'La loca',
  'La family',
  'Gerry',
  'Sr. Zamora',
  'Reunión',
  'Carlos',
  'Daniel',
  'Notas',
  'Los memes',
  'Antonio',
  'Ingrid',
];

List<String> mensajes = [
  '¿Qué se arma hoy?',
  'Como que tengo flojera',
  'Ya te mandé lo que me pediste',
  'Dejame ver si puedo',
  'Aún no hago nada, pero ya',
  'Bien, y tú?',
  'Mañana te paso lo que te debo, ahora sí',
  '¿Ya encontraste tu cosa?',
  'Vamos a tomar!',
  'Jajajaja claro que no',
  'Ya no hay leche, voy',
  'Yo igual te quiero hommie',
  'Su proyecto queda listo en 4 días',
  'La próxima semana sí',
  'Yo no quiero ir, pero x',
  'Te veo mañana entonces',
  'Comprar leche',
  'Foto',
  '¿Ya hiciste tu parte?',
  '¿Ya conseguiste otro gato?',
];

List<bool> leidos = [
  true,
  false,
  false,
  true,
  true,
  true,
  false,
  true,
  false,
  true,
  true,
  false,
  false,
  true,
  true,
  false,
  true,
  false,
  true,
  true,
];
